/* Editorial expansion based on the supplied resume, report, research presentation, and internship showcase. */
const byId = Object.fromEntries(window.PROJECTS.map(p=>[p.id,p]));
Object.assign(byId.carbondale,{
 shortTitle:'A citywide view of flood risk.',cardDescription:'A 92 mi² rain-on-grid model, eighteen storms, and a framework for comparing detention and distributed BMPs.',group:'research',cardImage:'inundation-mapping-for-carbondale.webp',metric:'92 mi² · 18 scenarios',period:'2025 — PRESENT',title:'Carbondale stormwater master planning',
 metrics:[['92 mi²','Contributing watershed'],['~357,000','Computational cells'],['18','Design-storm scenarios']],
 images:[['hec-ras-2d-for-carbondale-mesh-generation.webp','HEC-RAS 2D model, channel breaklines, and local mesh refinement.'],['inundation-mapping-for-carbondale.webp','Carbondale inundation mapping comparing supplied storm scenarios. Original legends and scenario labels are preserved.'],['inundation-mapping-for-carbondale-2.webp','A second mapped corridor showing how modeled inundation changes across storm scenarios.'],['city-scale-pcswmm-modeling-for-the-city-of-carbondale.webp','Citywide PCSWMM network used in the separate pluvial and BMP assessment.'],['quarterly-meeting-3-pdf-page-24.webp','The five BMP configurations used for scenario testing; these are modeling configurations rather than construction specifications.'],['bioretention-cell-and-infiltration-trench.webp','Bioretention and infiltration trench conceptual layer configurations from the research presentation.'],['rain-garden-vegetative-swale-and-rain-barrel.webp','Surface and source controls: rain garden, vegetative swale, and rain barrel.'],['infiltration-trench-at-node-j1204.webp','Infiltration trench hydrograph comparisons at control node J1204.'],['infiltration-trench-at-node-j3375.webp','Infiltration trench hydrograph comparisons at control node J3375.'],['rain-barrel-at-node-j1021.webp','Rain barrel scenario comparison at control node J1021.'],['rain-barrel-at-node-j3375.webp','Rain barrel scenario comparison at control node J3375.']],
 video:['carbondale-model.mp4','carbondale-model-poster.jpg','Carbondale event-model animation. This supplied clip illustrates simulated inundation progression, not observed flooding.'],
 methods:[
 ['A consistent geospatial foundation','The team’s watershed model combines 1-meter USGS 3DEP LiDAR terrain with NLCD land cover and SSURGO hydrologic soil groups. I connected these spatial inputs to terrain processing, roughness assignment, and a cell-based SCS Curve Number grid. Keeping the physical data framework consistent across analyses makes the scenario comparisons easier to trace and explain.'],
 ['Hydraulic connectivity before computation','Bare-earth terrain can represent road and railway embankments as solid barriers, even where water passes through a culvert or beneath a bridge. Preliminary runs helped identify substantial upstream impoundments. The team checked candidate locations against aerial imagery and field information, then introduced terrain flow paths at confirmed crossings and reran the model. This iterative conditioning addressed false barriers before interpreting flood patterns.'],
 ['A mesh that respects the landscape','The approximately 92-square-mile domain used a nominal 150-foot grid with roughly 357,137 computational cells. Breaklines followed streams and roads, with local refinement to 25 feet to better represent channel alignments and embankment crests. The 1-meter terrain resolution and computational-cell dimensions describe different parts of the model; a fine terrain dataset does not mean every computational cell is 1 meter.'],
 ['Spatially explicit roughness and rainfall losses','Manning’s n was assigned by land-cover class. Because 30-meter land cover does not reliably resolve narrow channels, principal channel areas were digitized using terrain and imagery and reclassified as open water, receiving n = 0.035. The NLCD–SSURGO overlay informed the Curve Number grid, with average antecedent moisture and initial abstraction of 0.2S. The predominantly C and D soils within the city constrain infiltration performance.'],
 ['A deliberate storm-scenario matrix','Six recurrence intervals—2, 5, 10, 25, 50, and 100 years—were crossed with 3-, 6-, and 24-hour durations. Bulletin 75 rainfall depths for southern Illinois were distributed with Huff first-quartile patterns for 3- and 6-hour storms and third-quartile patterns for 24-hour storms. This tests duration and temporal distribution together, rather than treating total rainfall depth as a complete description of flood response.'],
 ['Rain-on-grid inundation and diagnostic review','HEC-RAS 6.6 applied rainfall directly to the 2D mesh, representing rainfall losses, runoff, overland routing, channel flow, and surface storage in one terrain-based model. The reported configuration used diffusion-wave equations and a 30-second base time step. Maximum-depth rasters supported consistent cross-scenario mapping and review against city-reported flood complaint locations. Spatial agreement with complaints is a useful reasonableness check, distinct from calibration to measured discharge.'],
 ['Detention as a screening problem','Three candidate locations were examined. The report presents Pond A as a representative concept with about 5 acres of surface area and 6 feet of average depth. Terrain-integrated storage and a single outlet were evaluated for twelve recurrence–duration combinations. At Location A, the reported 25-year, 3-hour peak changed from 95.4 to 8.0 cfs; the 25-year, 24-hour peak changed from 28.4 to 22.6 cfs. The contrast demonstrates why the critical storm matters more than a single headline percentage.'],
 ['A complementary pluvial model','The approximately 18-square-mile PCSWMM model represents rainfall-driven drainage within the city. Terrain-based subcatchments target about 10 acres, with fractional imperviousness and the same land-cover/soil framework. Because the available pipe inventory contained connectivity and attribute gaps, the documented framework used terrain-derived routing and provisional 3-foot circular conduits for comparative assessment. The riverine and pluvial models were analyzed separately in this phase.'],
 ['Controlled comparison of distributed BMPs','The scenario framework evaluates bioretention cells, infiltration trenches, rain gardens, rain barrels, and vegetative swales individually at 10%, 20%, and 30% treatment of impervious area. Holding the routing network constant helps isolate the modeled effect of each intervention. Python-supported comparisons examine peak discharge, runoff volume, and peak timing at control nodes. The subsequent presentation includes site-level hydrograph comparisons at J1021, J1204, and J3375.'],
 ['Translating results into a planning conversation','The work connects mapped exposure, complaint locations, detention performance, and BMP comparisons to the city’s stormwater planning questions. Where large detention sites are constrained, distributed controls offer a different intervention scale. The next research task described in the presentation is a future-climate framework using seven candidate NARCCAP GCM–RCM pairs at approximately 50-kilometer resolution for 2041–2070. The proposed workflow screens historical fit, applies bias correction against observed rainfall, and examines 3-, 6-, and 24-hour extremes; this is planned work, not a completed future-flood finding.']
 ],
 scope:'These are planning-level research results from an ungauged basin, without discharge calibration. Regulated Crab Orchard Lake dam outflows are excluded. The HEC-RAS and PCSWMM analyses are decoupled, so coincident creek backwater at sewer outfalls is not quantified. The provisional PCSWMM conveyance network supports comparative screening rather than verification of as-built pipe capacity. Detention siting, utilities, permitting, overflow routing, freeboard, and construction design require further investigation.',
 sources:'Technical basis: Quarterly Meeting II Report, sections 2–6 and Tables 3, 5, and 6; Quarterly Meeting III research presentation. Research led by Ajay Kalra, Ph.D., P.E., Southern Illinois University Carbondale. Personal contributions and responsibilities follow the supplied résumé and project description.'
});
Object.assign(byId.bridgewatch,{
 shortTitle:'Flood monitoring, grounded in hydrology.',cardDescription:'A reproducible assessment of bridge–gage relationships that goes beyond the nearest point on a map.',group:'infrastructure',cardImage:'bridge-gage-connection-assessment-in-arcgis-pro.webp',metric:'650+ bridges assessed',period:'SUMMER 2026',title:'BridgeWatch monitoring assessment',
 metrics:[['650+','Connections audited'],['150','New pairings recommended'],['180','Pairings flagged for disconnection']],
 images:[['bridge-gage-connection-assessment-in-arcgis-pro.webp','Bridge–gage connection assessment map in ArcGIS Pro. The original legend distinguishes bridge and gage locations and drainage context.'],['during-my-internship-at-hanson.webp','At Hanson Professional Services during the summer 2026 water resources internship.']],
 methods:[['Hydrologic relevance before proximity','A nearby gage can lie outside the contributing drainage system of a bridge. I assessed the connection in a hydrologic context, reviewing whether the gage and bridge are on the same river system, their catchment overlap, and the relationship between their drainage areas. This addressed the underlying question: how representative is the gage for the bridge’s contributing runoff?'],['Explicit screening criteria','The internship showcase describes catchment containment fraction and drainage-area ratio as screening measures, along with river connectivity and proximity. Its simplified decision tree uses a drainage-area ratio interval of 0.5 to 1.5 as one review criterion. This was a project screening rule used alongside other evidence, rather than a universal standard for pairing any bridge and gage.'],['A repeatable Python–GIS pipeline','I built the analysis workflow using Python and ArcGIS Pro, organizing spatial relationships and connection decisions into a master bridge database. The resulting inventory could be filtered in Excel and symbolized in GIS, making large-scale review and individual recommendations part of the same traceable workflow.'],['Actionable recommendations at statewide scale','The showcase records 650+ connections audited, 150 new pairings recommended for unconnected bridges, and 180 existing pairings deemed unsuitable and recommended for disconnection. Keep, review, and disconnect classifications provided an explicit next action for engineering review. These counts describe recommendations, not confirmed changes to the operational system.'],['Field feedback for warning performance','I created an inspection form to support engineering review of alert thresholds after major storm alerts. The showcase recommends regional threshold recalibration and reassessment following major events. USGS streamgages and NEXRAD ground-based radar provide different types of observations; precipitation-product coverage is part of the monitoring strategy, not an interchangeable stream-stage measurement.']],
 scope:'Recommendation counts are reported in the 2026 internship showcase. This case study does not claim that all recommendations were implemented or that a measured improvement in warning accuracy or lead time was demonstrated.',sources:'Technical basis: 2026 Intern Project Showcase, BridgeWatch workflow and results slides; résumé and supplied project description.'
});
Object.assign(byId.culverts,{
 shortTitle:'Drainage design, from basin to crossing.',cardDescription:'GIS-derived hydrology and HydroCAD analysis supporting culvert sizing, headwater review, and overtopping assessment.',group:'infrastructure',cardImage:'hydrocad-culvert-design.webp',metric:'30+ culvert designs',period:'SUMMER 2026',title:'Highway drainage & culvert design',metrics:[['30+','Culvert designs supported'],['GIS → hydraulics','Connected design workflow']],
 images:[['hydrocad-culvert-design.webp','HydroCAD culvert configuration and headwater analysis.'],['hydrocad-hydraulic-anlaysis-of-culvert.webp','HydroCAD model schematics supporting culvert hydraulic analysis.'],['automating-gis-tasks-using-modelbuilder.webp','ArcGIS ModelBuilder workflow used to automate GIS processing tasks.'],['reach-length-and-slope.webp','Terrain-profile review supporting reach length and slope extraction.']],
 methods:[['Catchment definition and geometric inputs','I delineated contributing watersheds in ArcGIS Pro and extracted drainage areas, perimeters, flow paths, reach lengths, slopes, and other basin parameters used in the design workflow. Terrain profiles and mapped drainage paths linked the modeled catchment to the physical crossing.'],['Land cover and runoff characterization','Land-cover assignment and curve-number generation translated GIS information into runoff inputs. The internship showcase describes using curve-number-based runoff or the rational method as appropriate to the design analysis. The selected hydrologic representation informs the inflow condition used for structure sizing.'],['Hydraulic sizing and roadway performance','I used HydroCAD to evaluate culvert alternatives and assess the relationship between headwater elevation and the road crest. Comparing alternatives around an explicit overtopping criterion connects hydraulic output to the actual roadway performance question.'],['Repeatable production support','Advanced Excel and Bentley OpenRoads supported calculations and engineering design coordination across interstate highway projects. ModelBuilder automation supported recurring GIS tasks. The showcase documents work on more than 30 culverts during the internship.']],scope:'Design support was performed within the Hanson engineering team. Structure-specific dimensions, adopted frequencies, and final approvals are not presented here.',sources:'Technical basis: 2026 Intern Project Showcase, culvert design slide; supplied HydroCAD, GIS, and terrain-profile images; résumé.'
});
Object.assign(byId.srh2d,{
 shortTitle:'Resolving flow at a highway crossing.',cardDescription:'Terrain, materials, breaklines, mesh generation, and SRH-2D analysis with HY-8 culvert structures.',group:'infrastructure',cardImage:'culvert-modeling-in-srh-2d.webp',metric:'2D hydraulic modeling',period:'SUMMER 2026',title:'Interstate crossing: SRH-2D hydraulics',metrics:[['SRH-2D','Two-dimensional analysis'],['HY-8','Culvert structures']],images:[['culvert-modeling-in-srh-2d.webp','SRH-2D modeling workflow at the highway crossing, showing terrain, mesh, and aligned breakline arcs.']],methods:[['Terrain and hydraulic-material preparation','I prepared terrain and GIS layers in ArcGIS Pro and categorized land cover for hydraulic-material assignment. This establishes the spatial information used to represent surface resistance and the shape of the flow domain.'],['Breaklines and computational geometry','Breakline arcs and mesh generation formed a continuous workflow from GIS preparation to model development. Aligning computational geometry with important terrain features supports a more meaningful representation of the highway corridor and crossing approaches.'],['Boundary and structure configuration','I set up boundary conditions and incorporated HY-8 culvert structures in the SRH-2D workflow. The model combines the spatial behavior of flow around the crossing with the hydraulic representation of the culverts.'],['Flow analysis for design support','I performed two-dimensional flow analysis to support detailed bridge and culvert design at the critical highway section. This work extends the basin-to-culvert workflow by resolving spatial flow patterns around infrastructure.']],sources:'Technical basis: supplied SRH-2D model image, résumé, and project description.'
});
Object.assign(byId['dam-removal'],{shortTitle:'Hydraulics for dam-removal planning.',cardDescription:'A one-dimensional HEC-RAS model and accumulated sediment-volume estimate supporting project planning.',group:'infrastructure',metric:'HEC-RAS 1D',period:'SUMMER 2026',title:'Dam removal: hydraulics & sediment volume',typeStyle:'sediment-art',typeNumber:'1D',typeLabel:'Hydraulic conditions. Accumulated sediment. Better planning inputs.',metrics:[['HEC-RAS 1D','Hydraulic model'],['Sediment volume','Planning estimate']],images:[],methods:[['Model development','I developed a one-dimensional HEC-RAS model to represent hydraulic conditions within the dam-removal project area.'],['Sediment-volume assessment','I estimated accumulated sediment volume to provide the engineering team with a quantity for planning and design discussions.'],['Interpreting the estimate','Hydraulic analysis and accumulated-volume estimation support understanding the existing project setting. The scope here is a volume estimate; it is not a prediction of post-removal sediment transport, water quality, or channel evolution.']],sources:'Technical basis: résumé and supplied project description.'});
Object.assign(byId.melamchi,{shortTitle:'Spatial intelligence for a water network.',cardDescription:'GIS asset management, DGPS verification, and field-team training for the Melamchi Water Supply Project.',group:'gis',metric:'125+ miles of pipelines',period:'2024 — 2025',title:'Melamchi water-distribution GIS',typeStyle:'gis-art',typeNumber:'125+ mi',typeLabel:'A connected record of Kathmandu’s water-distribution infrastructure.',metrics:[['125+ mi','Pipeline-network GIS coverage'],['DGPS','Field asset verification']],images:[],methods:[['Network and asset-record stewardship','I led GIS data management for the distribution pipeline network, reviewing and updating geospatial datasets to maintain spatial integrity and an accurate asset inventory. The project forms part of the national-scale initiative delivering potable water to Kathmandu.'],['Field verification with DGPS','I planned and executed DGPS-based surveys to verify asset locations. Connecting field observations to the office GIS workflow helped reconcile the infrastructure record with the assets on the ground.'],['Engineering maps and recommendations','I produced data-driven reports and engineering maps that supported pipeline operational review and cost-effective infrastructure upgrade planning. The deliverables translated the spatial inventory into information that the project team could use.'],['Capacity building for survey teams','I led hands-on training in geospatial data collection and quality control. Training made the data process transferable to field teams and supported consistency across subsequent survey work.']],sources:'Technical basis: résumé and supplied Melamchi project description.'});
Object.assign(byId.asce,{shortTitle:'Coordinating an engineering community.',cardDescription:'Communications leadership across judges, students, faculty, volunteers, and officials for a three-day regional symposium.',group:'gis',metric:'500+ students · 17 universities',period:'2025 — 2026',title:'ASCE Mid-America Student Symposium',typeStyle:'leadership-art',typeNumber:'17',typeLabel:'Universities connected through one coordinated event.',metrics:[['500+','Student attendees'],['35+','PE judges'],['3 days','Regional symposium']],images:[],methods:[['A single communication point','As communications lead, I connected judges, students, volunteers, faculty, staff, and event officials across the symposium co-hosted by SIUC and SIUE. The role required consistent information across many independent responsibilities.'],['Documentation and competition information','I drafted event materials including ASCE mailers, website content, and rules and rubrics for local competitions. Banners and posters extended that information into the event environment.'],['Judge coordination','I recruited and coordinated more than 35 PE judges for society-wide, regional, and local competitions, including training and accommodation arrangements.'],['Schedules, venues, and volunteers','I coordinated event schedules and the project timeline, supported venue management, and assigned and managed volunteers. These linked responsibilities served more than 500 student attendees from 17 universities over three days.']],sources:'Technical basis: résumé and supplied symposium leadership description.'});
window.PROJECTS.push({id:'naperville',org:'Naperville stormwater study',role:'PCSWMM modeling & BMP assessment',date:'Ongoing work',period:'ONGOING',group:'research',category:'STORMWATER & BMP EVALUATION',title:'Naperville stormwater network & BMP study',shortTitle:'Understanding the network. Testing the relief.',cardDescription:'PCSWMM network modeling and pipe-flow visualization to investigate a suitable BMP for reducing stormwater flooding.',cardImage:'gis-layout-of-naperville-stormwater-network.webp',metric:'PCSWMM · ongoing assessment',summary:'I am using PCSWMM to investigate stormwater network behavior in Naperville and identify an appropriate best management practice to reduce flooding. GIS mapping and a pipe-flow animation communicate the modeled system and support the ongoing assessment.',problem:'The study asks which BMP is appropriate for relieving flooding within the modeled stormwater system. Understanding how runoff enters and moves through the pipe network provides the context for evaluating an intervention.',contribution:'My work includes PCSWMM modeling, GIS representation of the stormwater network, and investigation of pipe-flow behavior as part of the BMP assessment.',tags:['PCSWMM','Stormwater networks','GIS','BMP assessment'],metrics:[['PCSWMM','Network modeling'],['BMP selection','Ongoing investigation']],details:['Mapped the Naperville stormwater network in GIS.','Developed and reviewed the PCSWMM model representation.','Used pipe-flow animation to communicate system behavior.','Investigated an appropriate BMP to reduce flooding.'],decision:'The aim is to connect the location and behavior of modeled flooding to a suitable intervention. Final BMP selection and quantified performance will follow the ongoing assessment.',images:[['gis-layout-of-naperville-stormwater-network.webp','GIS layout of the Naperville stormwater network.'],['pcswmm-model-naperville.webp','PCSWMM model view of the Naperville study area.']],video:['naperville-model.mp4','naperville-model-poster.jpg','Pipe-flow animation from the Naperville PCSWMM model.'],methods:[['Establish the spatial network','The GIS layout documents the stormwater network and the spatial context for the PCSWMM study. This helps connect network elements to the modeled drainage system.'],['Inspect dynamic pipe behavior','The supplied animation shows the pipe-flow representation during a model run. It supports visual examination and communication of changing system behavior.'],['Investigate mitigation options','The ongoing objective is to identify a suitable BMP to reduce flooding. Final selection, implementation extent, and numerical benefits remain under evaluation and are not inferred from the animation alone.']],scope:'Ongoing assessment. No final BMP choice, calibrated performance result, or implemented flood reduction is claimed.',sources:'Technical basis: supplied Naperville GIS layout, PCSWMM screenshot, pipe-flow video, and project description.'});
window.PROJECTS.sort((a,b)=>['carbondale','bridgewatch','culverts','srh2d','naperville','melamchi','dam-removal','asce'].indexOf(a.id)-['carbondale','bridgewatch','culverts','srh2d','naperville','melamchi','dam-removal','asce'].indexOf(b.id));
window.SCENARIOS=[
[5,3,28.9,2,93.1],[5,6,39.5,3.8,90.4],[5,24,18,6.8,62.2],
[25,3,95.4,8,91.6],[25,6,72.4,12.5,82.7],[25,24,28.4,22.6,20.4],
[50,3,119.4,14.1,88.2],[50,6,90,19.7,78.1],[50,24,33.4,27,19.2],
[100,3,149,22,85.2],[100,6,108,26,75.9],[100,24,39,33,15.4]
];
window.METHODS=[
{title:'Start with the physical system.',text:'Terrain, land cover, soils, and infrastructure records establish the foundation. In Carbondale, 1-meter LiDAR terrain, NLCD, and SSURGO link watershed characteristics to model parameters. At a culvert, GIS-derived basin geometry connects the catchment to the crossing.',image:'automating-gis-tasks-using-modelbuilder.webp',alt:'ArcGIS ModelBuilder geoprocessing workflow',output:'OUTPUT / Traceable spatial inputs and repeatable GIS processing'},
{title:'Make the geometry work hydraulically.',text:'A model needs the right flow connections. Terrain conditioning at confirmed crossings, channel breaklines, mesh refinement, and material assignment make the numerical representation more faithful to the landscape being assessed.',image:'hec-ras-2d-for-carbondale-mesh-generation.webp',alt:'HEC-RAS mesh and breaklines for Carbondale',output:'OUTPUT / Terrain, mesh, and parameters connected to physical features'},
{title:'Test the question from more than one angle.',text:'The Carbondale study crosses six return periods with three storm durations. BridgeWatch screening considers catchment overlap and drainage-area relationships as well as distance. The point is to understand what controls the answer.',image:'inundation-mapping-for-carbondale.webp',alt:'Comparative Carbondale inundation maps with storm labels and depth legends',output:'OUTPUT / A structured comparison of scenarios and controlling conditions'},
{title:'Hold the baseline. Change the intervention.',text:'Detention and BMP comparisons use a consistent baseline so that differences can be attributed to the modeled intervention. Peak flow, total runoff volume, and peak timing each describe a different aspect of performance.',image:'infiltration-trench-at-node-j1204.webp',alt:'Infiltration trench scenario hydrographs at node J1204',output:'OUTPUT / Site-specific performance comparisons with clear assumptions'},
{title:'Translate analysis into the next action.',text:'A useful deliverable connects the result to a decision: a bridge connection to review, a culvert size to assess, a candidate mitigation measure, or a location needing field verification. Maps, traceable recommendations, and clear communication complete that connection.',image:'bridge-gage-connection-assessment-in-arcgis-pro.webp',alt:'GIS map documenting bridge and streamgage relationships',output:'OUTPUT / Engineering maps, recommendations, and focused follow-up'}
];
